spring:
  application:
    name: springboot-nyano
  datasource:
    url: jdbc:mysql://localhost:3306/shopdevgo
    username: root
    password: 060802
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  mail:
    port: 465
    host: xxxx
    password: aaaa
    username: aaaa
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true